name: analyzer_x_server
description: Git analysis backend server
version: 1.0.0

publish_to: none
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  args: ^2.4.2
  analyzer_x:
    path: ../analyzer_helper
  logging: ^1.2.0